--------------------------------------------------------
--  File created - Tuesday-July-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERDETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMERDETAILS" 
   (	"ACCOUNTNUMBER" NUMBER(20,0), 
	"AGE" VARCHAR2(10 BYTE), 
	"CUSTOMERNAME" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER(20,0), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"MOBILENUMBER" VARCHAR2(20 BYTE), 
	"ACCOUNTTYPE" VARCHAR2(30 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"ATMPIN" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMERDETAILS
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMERDETAILS (ACCOUNTNUMBER,AGE,CUSTOMERNAME,BALANCE,ADDRESS,MOBILENUMBER,ACCOUNTTYPE,GENDER,ATMPIN) values (1,'22','Akash',45000,'Chennai','7904595924','savings','Male','9956');
